#
  # SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
  #
  # SPDX-License-Identifier: Apache-2.0
#
storage:
  type: "default"  # type could be default or flutter_secure

openid:
  enabled: true
  type: keycloak
  credential:
    issuerBaseUrl: "https://cms-cdn.yo-digital.com/auth/realms/cms"
    client_id: "oneai-arcview-dev"
    client_secret: "tHzd2a1aD3BuXbfprmgLOKvEa2vDEPqN"
    redirect_base_url: "http://localhost:9876" #this property will be used form macos(desktop) or desktop application
    call_back_path: "/callback"
    scopes:
      - "openid"
      - "profile"
      - "email"
    redirect_deeplink_url: "com.example.app://callback"