#
  # SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
  #
  # SPDX-License-Identifier: Apache-2.0
#
storage:
  type: "default"  # type could be default or secure

openid:
  enabled: true
  type: keycloak
  credential:
    issuerBaseUrl: ${ARC_VIEW_ISSUER_BASE_URL}
    client_id: ${ARC_VIEW_OIDC_CLIENT_ID}
    client_secret: ${ARC_VIEW_OIDC_CLIENT_SECRET}
    redirect_base_url: ${ARC_VIEW_REDIRECT_BASE_URL} #this property will be used form macos(desktop) or desktop application
    call_back_path: "/callback"
    scopes:
      - "openid"
      - "profile"
      - "email"
    redirect_deeplink_url: "com.example.app://callback"
